Lidar_front_end:
   lidar_type: 3   # 1 for Livox-avia, 3 for Ouster-OS1-64
   N_SCANS: 64
   using_raw_point: 1
   point_step: 3
   
r3live_common:
   if_dump_log: 0                   # If recording ESIKF update log. [default = 0]
   record_offline_map: 0            # If recording offline map. [default = 1]
   pub_pt_minimum_views: 3          # Publish points which have been render up to "pub_pt_minimum_views" time. [default = 3]
   minimum_pts_size: 0.01           # The minimum distance for every two points in Global map (unit in meter). [default = 0.01] 
   image_downsample_ratio: 1        # The downsample ratio of the input image. [default = 1]
   estimate_i2c_extrinsic: 1        # If enable estimate the extrinsic between camera and IMU. [default = 1] 
   estimate_intrinsic: 0            # If enable estimate the online intrinsic calibration of the camera lens. [default = 1] 
   maximum_vio_tracked_pts: 600     # The maximum points for tracking. [default = 600]
   append_global_map_point_step: 4  # The point step of append point to global map. [default = 4]

r3live_vio:
   image_width: 800
   image_height: 592
   camera_intrinsic:
      [644.050732, 0.0, 642.929002, 0.0, 415.052939, 292.805719, 0.0, 0.0, 1.0]  
   camera_dist_coeffs: [-0.064607, 0.068076, -0.000984, -0.000173, 0.0 ]  #k1, k2, p1, p2, k3
   # Fine extrinsic value. form camera-LiDAR calibration.
   camera_ext_R: [ 0.0,  0.0,  1.0,
           -1.0,  0.0,  0.0, 
           0.0,  -1.0,  0.0]
   camera_ext_t: [0.14045697042661232, -0.2008769352431301, -0.3602922740243528]
  #  camera_ext_t: [-0.3608, 0.1930, -0.2029]
  #  camera_ext_R: [ 0.0028648,  0.9999713, -0.0070168,
  #                   0.0296777, -0.0070988, -0.9995343,
  #                   -0.9995554,  0.0026553, -0.0296972]
  #  camera_ext_t: [0.14118513, 0.1552482, 0.01917531]
   
r3live_lio:        
   lio_update_point_step: 2   # Point step used for LIO update.  
   max_iteration: 10           # Maximum times of LIO esikf.
   lidar_time_delay: 0  # The time-offset between LiDAR and IMU, provided by user. 
   filter_size_corner: 0.3   
   filter_size_surf: 0.3
   filter_size_surf_z: 0.3
   filter_size_map: 0.3
   lidar_imu_rotm:
      [ -1.0000000,  0.0000000, -0.0000000,
        -0.0000000, -1.0000000, -0.0000000,
        -0.0000000, -0.0000000,  1.0000000] 
   lidar_imu_t: [-0.00625300054647937, 0.011774999709786016, -0.028534999999999977]
  #  lidar_imu_rotm:
  #     [ 1, 0, 0,
  #     0, 1, 0,
  #     0, 0, 1] 
  #  lidar_imu_t: [0, -0,  0]