Lidar_front_end:
   lidar_type: 2   # 1 for Livox-avia, 3 for Ouster-OS1-64
   N_SCANS: 16
   using_raw_point: 1
   point_step: 1
   blind: 6
   
r3live_common:
   if_dump_log: 0                   # If recording ESIKF update log. [default = 0]
   record_offline_map: 0            # If recording offline map. [default = 1]
   pub_pt_minimum_views: 3          # Publish points which have been render up to "pub_pt_minimum_views" time. [default = 3]
   minimum_pts_size: 0.01           # The minimum distance for every two points in Global map (unit in meter). [default = 0.01] 
   image_downsample_ratio: 1        # The downsample ratio of the input image. [default = 1]
   estimate_i2c_extrinsic: 1        # If enable estimate the extrinsic between camera and IMU. [default = 1] 
   estimate_intrinsic: 1            # If enable estimate the online intrinsic calibration of the camera lens. [default = 1] 
   maximum_vio_tracked_pts: 600     # The maximum points for tracking. [default = 600]
   append_global_map_point_step: 4  # The point step of append point to global map. [default = 4]

r3live_vio:
   image_width: 1224
   image_height: 1024
   camera_intrinsic:
      [1172.771733138536,    0.0,            617.941545715258, 
             0.0,            1172.364005984343, 507.672727295385, 
             0.0,               0.0,              1.0]  
   camera_dist_coeffs: [-0.052628389768906, 0.100832689624109, 0.000395112517197, 0.000362060505238, 0.0 ]  #k1, k2, p1, p2, k3
   # Fine extrinsic value. form camera-LiDAR calibration.
   camera_ext_R: [0.016401767702498, -0.010112948899873,  0.999814337905184, 
         -0.999053252579189, -0.040462795913874,  0.015980008065579,  
          0.040293678501436, -0.999129866639658, -0.010767035870758]
   camera_ext_t: [ 0.128861294507233,  0.196875730840019, -0.126632260291528]
   
r3live_lio:        
   lio_update_point_step: 3   # Point step used for LIO update.  
   max_iteration: 10           # Maximum times of LIO esikf.
   lidar_time_delay: 0  # The time-offset between LiDAR and IMU, provided by user. 
   filter_size_corner: 0.2   
   filter_size_surf: 0.2
   filter_size_surf_z: 0.2
   filter_size_map: 0.2
   lidar_imu_rotm:
      [ 0.9995  , -0.0316 ,   0.0094 ,
        0.0316   , 0.9995  , -0.0006 ,
              -0.0094  ,  0.0009 ,   1.0000  ] 
   lidar_imu_t: [0.0477, -0.1441,  0.0101]